apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
  labels:
    console.openshift.io/terminal: "true"
  name: web-terminal-tooling
  namespace: openshift-operators
spec:
  components:
  - container:
      args:
      - tail
      - -f
      - /dev/null
      cpuLimit: 400m
      cpuRequest: 100m
      image: quay.io/wzzrd/web-terminal-cnp:latest
      memoryLimit: 512Mi
      memoryRequest: 128Mi
      mountSources: false
      sourceMapping: /projects
    name: web-terminal-tooling
