apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 labels:
   operators.coreos.com/cloud-native-postgresql.openshift-operators: ""
   name: cloud-native-postgresql
   namespace: openshift-operators
spec:
  channel: stable-v1.20
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cloud-native-postgresql.v1.20.2
