apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-volume-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

