apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-client
  namespace: minio-tenant
spec:
  host: minio-client-minio-tenant.apps.sno.thuisnet.lan
  port:
    targetPort: https-minio
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
