apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio-tenant
  labels:
    app: minio
spec:
  features:
    bucketDNS: false
    domains: { }
  users:
    - name: storage-user
  buckets:
    - name: database-backups
  certConfig: { }
  podManagementPolicy: Parallel
  configuration:
    name: storage-configuration
  env: [ ]
  serviceMetadata:
    minioServiceLabels: { }
    minioServiceAnnotations: { }
    consoleServiceLabels: { }
    consoleServiceAnnotations: { }
  priorityClassName: ""
  externalCaCertSecret: [ ]
  externalCertSecret: [ ]
  externalClientCertSecrets: [ ]
  image: quay.io/minio/minio:RELEASE.2023-09-04T19-57-37Z
  imagePullSecret: { }
  mountPath: /export
  subPath: ""
  serviceAccountName: ""
  pools:
    - servers: 2
      name: pool-0
      topologySpreadConstraints: [ ]
      volumesPerServer: 2
      nodeSelector: { }
      tolerations: [ ]
      affinity:
        nodeAffinity: { }
        podAffinity: { }
        podAntiAffinity: { }
      resources: { }
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: { }
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: lvms-local-lvm
        status: { }
      securityContext: {}
      containerSecurityContext: {}
  requestAutoCert: true
