kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edbuser04-promote
  namespace: edbuser04
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: edbuser04
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-psql-switchover-role
