apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: stable-v1.11.1
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV:  openshift-pipelines-operator-rh.v1.11.1
