apiVersion: v1
data:
  htpasswd: bWF4aW06JDJ5JDA1JC9sQ0JZVVpadTR4bm1Pdk1Ya2hzMWVvVG1HcDdmNWlia3NQUmhZWElEaDJSOTZnTkVJZEkuCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
