apiVersion: v1
kind: Namespace
metadata:
  name: edbuser10
  annotations:
    openshift.io/requester: edbuser10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: edbuser10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: edbuser10
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edbuser10-promote
  namespace: edbuser10
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: edbuser10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-psql-switchover-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edbuser10-postgresql-admin
  namespace: edbuser10
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: edbuser10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusters.postgresql.k8s.enterprisedb.io-v1-admin
