apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    openshift.io/cluster-monitoring: "true"
