apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs-auth-tooling
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: cluster/auth-tooling
    repoURL: https://github.com/maxim-edb/cluster-config.git
    targetRevision: aws
  syncPolicy:
    automated: {}
