apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  inputs:
    - application:
        selector:
          matchLabels:
            k8s.enterprisedb.io/podRole: instance
      name: edbuser-postgres-logs
  outputDefaults:
    elasticsearch:
      structuredTypeName: nologformat
  pipelines:
    - inputRefs:
        - edbuser-postgres-logs
      name: edbuser-postgres-logs
      outputRefs:
        - default
      parse: json
