kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edbuser11-postgresql-admin
  namespace: edbuser11
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: edbuser11
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusters.postgresql.k8s.enterprisedb.io-v1-admin
